---

- name: Check if OS is supported
  include_tasks: os-check.yml

- name: Debian Install Tasks
  include_tasks: pkg-debian/install-monit.yml
  when: ansible_os_family == "Debian"
  register: is_debian

- name: RedHat Install Tasks
  include_tasks: pkg-redhat/install-monit.yml
  when: ansible_os_family == "RedHat"
  register: is_redhat


