---
#- name: ensure monit installed
#  apt: name={{ packages }} state=present
#  vars:
#    packages:
#      - monit
#  environment:
#    RUNLEVEL: 1
#  when: is_debian == True
#  tags:
#    - monit
#
#- name: Download EPEL Repo
#  yum_repository:
#    name: epel
#    description: EPEL YUM repo
#    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
#  environment:
#    RUNLEVEL: 1
#  when: is_redhat == True
#  tags:
#    - monit
#
#- name: ensure monit installed
#  yum: name={{ packages }} state=present
#  when: is_redhat == True
#  vars:
#    packages:
#    - monit
#    - curl
#  tags:
#    - monit
#
#- name: get monit version
#  shell: "monit --version | grep version | awk '{print $5}' | cut -d'-' -f1"
#  register: mv_rs_stdout
#  ignore_errors: True
#  tags:
#    - monit
#    - monit-version
#
#- name: set monit version
#  set_fact:
#    mv_rs: "{{ mv_rs_stdout.stdout }}"
#    cacheable: true
#  tags:
#    - monit
#    - monit-version
#
#
#- name: stop monit
#  service: name=monit state=stopped
#  ignore_errors: true
#  when: monit_version != mv_rs
#
- name: monit dirs
  file: path={{ item }} state=directory
  with_items:
    - "/var/monit/"
    - "/var/lib/monit/"
    - "/etc/monit/"
  tags:
    - monit
#
#- name: /var/lib/monit/ dir
#  file: path={{ item }} state=directory
#  when: is_redhat == True
#  with_items:
#    - "/etc/monit/conf.d/"
#    - "/var/lib/monit/"
#  tags:
#    - monit

- name: download and unzip monit
  get_url: url=https://mmonit.com/monit/dist/binary/{{ monit_version }}/monit-{{ monit_version }}-linux-x64.tar.gz dest=/var/monit mode=0755
#  when: monit_version != mv_rs
  tags:
    - monit

- name: download and unzip monit
  unarchive: src=/var/monit/monit-{{ monit_version }}-linux-x64.tar.gz dest=/var/monit copy=no
#  when: monit_version != mv_rs
  tags:
    - monit

- name: monit bin
  command: cp /var/monit/monit-{{ monit_version }}/bin/monit /usr/bin/
#  when: monit_version != mv_rs
  tags:
    - monit

- name: transfer monit config /etc/monit/monitrc
  template: src=monit/monitrc.conf dest=/etc/monit/monitrc mode=0700
  tags:
    - monit

- name: transfer monit config /etc/monitrc
  template: src=monit/monitrc.conf dest=/etc/monitrc mode=0700
  tags:
    - monit

- name: transfer monit id /var/lib/monit/id
  template: src=monit/monit.id dest=/var/lib/monit/id mode=0700
  tags:
    - monit

#- name: transfer monit-config configuration
#  template: src={{ item }} dest=/etc/monit/conf.d/{{ item | basename }} mode=0777
#  with_fileglob:
#    - ../templates/monit/conf.d/*.*
#  tags:
#    - monit
#    - monit-config

- name: ensure monit reloaded
  shell: /bin/true
  ignore_errors: true
  notify:
    - reload monit
  tags:
    - reload-service

