---
## Copy keys files and configuration
- name: transfer ssh config /etc/ssh/ssh_config
  template:
    src: keys/ssh_config
    dest: /etc/ssh/ssh_config
    owner: root
  tags:
    - ssh-config
    - ssh-keys
    - keys-deploy

#- name: transfer global deployment Key id_rsa_deploy_all
#  template:
#    src: "./../_ssh/keys/deploy_key_gh_{{ env }}.pem"
#    dest: /root/.ssh/deploy_key_gh.pem
#    owner: root
#    group: root
#    mode: 0600
#    force: yes
#  ignore_errors: true
#  tags:
#    - ssh-keys
#    - keys-deploy
#    - keys-global-deploy

#- name: transfer user deployment Key ubuntu id_rsa_deploy_all
#  template:
#    src: "./../_ssh/keys/deploy_key_gh_{{ env }}.pem"
#    dest: /home/ubuntu/.ssh/deploy_key_gh.pem
#    owner: ubuntu
#    group: ubuntu
#    mode: 0600
#    force: yes
#  ignore_errors: true
#  tags:
#    - ssh-keys
#    - keys-deploy
#    - keys-ubuntu-deploy

# todo how to remove ensure only keys?
#- name: ssh keys base
#  authorized_key:
#    user: ubuntu
#    key: "{{ lookup('file', item ) }}"
#    exclusive: yes
#  with_fileglob:
#    - "./../_ssh/keys/base/authorized_keys.pub"
#  tags:
#    - keys
#    - ssh-keys
#    - ssh-keys-new

- name: ssh keys env
  authorized_key:
    user: ubuntu
    key: "{{ lookup('file', item ) }}"
  with_fileglob:
    - "./../_ssh/keys/{{ env }}/*.pub"
  tags:
    - keys
    - ssh-keys
    - ssh-keys-new

- name: ssh keys main env
  authorized_key:
    user: ubuntu
    key: "{{ lookup('file', item ) }}"
  with_fileglob:
    - "./../_ssh/{{ env }}-env*.pub"
  tags:
    - keys
    - ssh-keys
    - ssh-keys-new
