---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags
- name: debug
  debug: msg={{ [env,idx,ecname,ecnameidx] }}
  tags:
    - never
    - debug

- name: debug
  debug: msg={{ hostvars[inventory_hostname].tags }}
  tags:
    - never
    - debug


- name: include common debian
  import_tasks: common-debian.yml
  when: is_ubuntu == True
  tags:
    - common-deploy
    - common-pkgs

- name: include limits
  import_tasks: limits.yml
  tags:
    - limits-deploy

- name: include zsh ubuntu
  import_tasks: zsh.yml
  vars:
    user: ubuntu
  when: is_ubuntu == True
  tags:
    - common-deploy
    - zsh-deploy

- name: include zshroot
  import_tasks: zsh.yml
  vars:
    user: root
    home_dir: '/'
  tags:
    - common-deploy
    - zsh-deploy

- name: include keys
  import_tasks: keys.yml
  tags:
    - keys-deploy
    - common-deploy

- name: install filebeat
  import_tasks: filebeat.yml
  tags:
    - filebeat-deploy
    - common-deploy

