---
CONST_DRONE_GITHUB_CLIENT_ID: 8f7bae6755a6e42fb76d
CONST_DRONE_GITHUB_CLIENT_SECRET: 1755fd13472dd76a8e977c3551477818a4a3db63
CONST_DRONE_RPC_SECRET: 2aC1+ed5e9dab0b77f3045d37546a5ede0310=
CONST_DRONE_SERVER_HOST: drone.devtools.link
CONST_DRONE_SERVER_PROTO: https
CONST_DRONE_TLS_AUTOCERT: true
  # https://github.com/drone/drone/issues/2779
CONST_DRONE_USER_CREATE: username:octocat,admin:true
drone_user: drone
drone_group: drone




mount_path: "/data"
drone_runner_opt_dir: "/opt/drone-runner"
drone_runner_config_dir: "{{ drone_runner_opt_dir }}/config"
drone_runner_log_dir: "{{ mount_path }}/log/drone-server"
drone_runner_data_dir: "{{ mount_path }}/var/run/docker.sock"






