##############################################################################################
# LINKS - https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
##############################################################################################
version: "3.7"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ elastic_search_version }}
    container_name: es01_{{ env }}
    environment:
      node.name: "{{ elasticsearch_node_name }}"
      cluster.name: "{{ elasticsearch_cluster_name | mandatory }}"
      discovery.seed_hosts: "es02,es03"
      cluster.initial_master_nodes: "es01,es02,es03"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: '-Xms{{ elasticsearch_xmx }}m -Xmx{{ elasticsearch_xmx }}m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - {{ elasticsearch_data_dir_01 }}:/usr/share/elasticsearch/data
#      - {{ elasticsearch_backup_dir }}:/var/elasticsearch-backup
#      - {{ elasticsearch_config_dir }}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - {{ elasticsearch_port }}:9200
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ elastic_search_version }}
    container_name: es02_{{ env }}
    environment:
      node.name: "es02"
      cluster.name: "{{ elasticsearch_cluster_name | mandatory }}"
      discovery.seed_hosts: "es01,es03"
      cluster.initial_master_nodes: "es01,es02,es03"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: '-Xms{{ elasticsearch_xmx }}m -Xmx{{ elasticsearch_xmx }}m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - {{ elasticsearch_data_dir_02 }}:/usr/share/elasticsearch/data
#      - {{ elasticsearch_backup_dir }}:/var/elasticsearch-backup
#      - {{ elasticsearch_config_dir }}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge