---
- name: get list of directories
  shell: |
    echo "{{ var_list_dirs }}" > /tmp/dirs.txt
    cat /tmp/dirs.txt
  tags:
    - create-dir


- name: create dirs
  file:
    path: "{{ item|safe|trim }}"
    state: directory
    owner: "{{ var_user }}"
    group: "{{ var_group }}"
    mode: 0777
    recurse: yes
  changed_when: "False"
  with_lines: cat /tmp/dirs.txt
  tags:
    - create-dir


