version: '3'
services:
  drone-server:
    container_name: drone
    image: drone/drone:1
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - /var/lib/drone:/data
    restart: always
    env_file:
      - {{ drone_server_config_dir }}/drone_server.env






