---
- name: transfer monit-config configuration
  template:
    src: "{{ item }}"
    dest: "/etc/monit/conf.d/{{ item | basename }}"
    mode: 0777
  with_fileglob:
    - ../templates/monit-config/*.*
  tags:
    - monit
    - monit-config

- name: ensure monit reloaded
  shell: /bin/true
  ignore_errors: true
  notify:
    - reload monit
  tags:
    - reload-service
