- name: Install aptitude using apt
  apt:
    name=aptitude
    state=latest
    update_cache=yes
    force_apt_get=yes
  tags:
    - all
    - vm-required


- name: Install required system packages
  apt:
    name={{ item }}
    state=latest
    update_cache=yes
  loop:
    - apt-transport-https
    - jq
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - python-pip
    - virtualenv
    - python3-setuptools
    - vim
  tags:
    - all
    - vm-required



