
- name: Install required system packages
  apt:
    name: {{ item }}
    state: latest
    update_cache: yes
    upgrade: yes
# Remove useless packages from the cache
    autoclean: yes
# Remove dependencies that are no longer required
    autoremove: yes
  loop:
    - apt-transport-https
    - jq
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - python-pip
    - virtualenv
    - python3-setuptools
    - vim
    - aptitude
  tags:
    - all
    - vm-required



