---
- name: create drone dirs
  file:
    path: "{{ item|safe|trim }}"
    state: directory
    owner: "{{ drone_user }}"
    group: "{{ drone_group }}"
    mode: 0777
    recurse: yes
  changed_when: "False"
  with_items:
    - "{{ drone_runner_opt_dir }}"
    - "{{ drone_runner_log_dir }}"
    - "{{ drone_runner_config_dir }}"
    - "{{ drone_runner_data_dir }}"
  tags:
    - drone
    - drone-install
    - drone-cluster

- name: copy drone docker-compose file
  template:
    dest: "{{ drone_runner_opt_dir }}/docker-compose.yml"
    owner: "{{ drone_user }}"
    group: "{{ drone_group }}"
    mode: 0777
    src: docker-compose.yml
  tags:
    - drone
    - drone-install
    - drone-docker-compose
    - drone-cluster
    - drone-config
    - drone-config-main

- name: create drone configuration file
  template:
     dest: "{{ drone_runner_config_dir }}/{{ item | basename }}"
     owner: "{{ drone_user }}"
     group: "{{ drone_group }}"
     mode: 0777
     src: "{{ item }}"
  with_items:
    - drone_runner.env
  register: config_change
  tags:
    - drone
    - drone-install
    - drone-cluster
    - drone-user
    - drone-config
    - drone-config-main

- name: restart drone
  shell: /bin/true
  notify: restart docker-compose-drone-runner
  when: ( config_change is defined and config_change.changed )
