version: '3'
services:
  drone-agent:
    container_name: runner
    image: drone/drone-runner-docker:1
    ports:
      - 0.0.0.0:3000:80
    command: agent
    restart: always
    volumes:
      - {{ drone_runner_data_dir }}:/var/run/docker.sock
    env_file:
      - {{ drone_runner_config_dir }}/drone_runner.env
