- name: install monit
  hosts: local
  become: true
  vars:
    VAR_MONIT_VERSION: "5.26.0"
    VAR_INSTALL_SPECIFIC_VERSION: "True"
  roles:
    - { role: monit,                   tags: [ 'monit'       ] }