################ SAMPLE USAGE #################################################################################
# ansible-playbook playbook-install-jenkins-docker.yaml --tags="vm-required,docker,set-user,create-dir,jenkins"
###############################################################################################################

- name: install docker jenkins
  hosts: gcp2
  remote_user: codeaprendiz
  become: true
  vars:
##### CREATING REQUIRED USERS ##############
    user: "jenkins"
    group: "jenkins"
####### CREATING REQUIRED DIRECTORIES #####
    mount_path: "/data"
    jenkins_tmp_dir: "{{ mount_path }}/tmp/jenkins"
    jenkins_log_dir: "{{ mount_path }}/var/log/jenkins"
    jenkins_opt_dir: "{{ mount_path }}/opt/jenkins"
    jenkins_config_dir: "{{ mount_path }}/opt/jenkins/config"
    var_list_dirs:
      - "{{ mount_path }}"
      - "{{ jenkins_log_dir }}"
      - "{{ jenkins_opt_dir }}"
      - "{{ jenkins_config_dir }}"

####### jenkins VARIABLES ##########
    env: "dev"



  roles:
    - { role: commons,                              tags: [ 'commons' ]}
    - { role: docker,                              tags: [ 'docker' ]}
    - { role: user,                                 tags: [ 'user'       ] }
    - { role: directory,                            tags: [ 'directory'] }
    - { role: jenkins-docker,                            tags: [ 'jenkins-docker'] }
