- name: create user
  hosts: local
  become: true
  roles:
    - role: commons
        tags: [ vm-required ]
    - role: user
        vars:
          VAR_USER: "elasticsearchcluster"
          VAR_GROUP: "elasticsearchcluster"
    - role: directory
        vars:
          VAR_CONTEXT: "elasticsearch-server"

