################ SAMPLE USAGE #################################################################################
#         ansible-playbook playbook-install-elastic-search-cluster-docker.yaml \
#         --tags="vm-required,set-user,create-dir"
###############################################################################################################

- name: create user
  hosts: local
  become: true
  vars:
##### CREATING REQUIRED USERS ##############
    VAR_USER: "elasticsearchcluster"
    VAR_GROUP: "elasticsearchcluster"
####### CREATING REQUIRED DIRECTORIES #####
    VAR_CONTEXT: "elasticsearch-server"
  roles:
    - { role: commons,                  tags: [ 'commons' ]}
    - { role: user,                   tags: [ 'user'       ] }
    - { role: directory,                   tags: [ 'directory'] }