################ SAMPLE USAGE #################################################################################
#         ansible-playbook playbook-install-elastic-search-cluster-docker.yaml \
#         --tags="vm-required,set-user,create-dir"
###############################################################################################################

- name: create user
  hosts: local
  become: true
  vars:
##### CREATING REQUIRED USERS ##############
    var_user: "elasticsearchcluster"
    var_group: "elasticsearchcluster"
####### CREATING REQUIRED DIRECTORIES #####
    var_context: "elasticsearch-server"
####### ELASTIC SEARCH VARIABLES ##########
    elastic_search_version: "7.8.0"
    env: "dev"
    elasticsearch_xmx: "512"
    elasticsearch_node_name: "es01"
    elasticsearch_cluster_name: "es-docker-cluster"

  roles:
    - { role: commons,                              tags: [ 'commons' ]}
    - { role: user,                                 tags: [ 'user'       ] }
    - { role: directory,                            tags: [ 'directory'] }
    - { role: elastic-search-cluster-docker,        tags: [ 'elastic-search-cluster-docker' ]}