- name: create user
  hosts: local
  become: true
  vars:
##### CREATING REQUIRED USERS ##############
    VAR_USER: "elasticsearchcluster"
    VAR_GROUP: "elasticsearchcluster"
####### CREATING REQUIRED DIRECTORIES #####
    VAR_CONTEXT: "elasticsearch-server"
  roles:
    - { role: commons,                      tags: [ 'vm-required' ]}
    - { role: user,                        tags: [ 'user'       ] }
    - { role: directory,                   tags: [ 'directory'] }