---
CONST_DRONE_GITHUB_CLIENT_ID: 8f7bae6755a6e42fb76d
CONST_DRONE_GITHUB_CLIENT_SECRET: 1755fd13472dd76a8e977c3551477818a4a3db63
CONST_DRONE_RPC_SECRET: 2aC1+ed5e9dab0b77f3045d37546a5ede0310=
CONST_DRONE_SERVER_HOST: droneio.gotdns.ch
CONST_DRONE_SERVER_PROTO: https
CONST_DRONE_TLS_AUTOCERT: true
  # https://github.com/drone/drone/issues/2779
CONST_DRONE_USER_CREATE: username:octocat,admin:true
drone_user: drone
drone_group: drone

mount_path: "/data"
drone_server_opt_dir: "/opt/drone-server"
drone_server_config_dir: "{{ drone_server_opt_dir }}/config"
drone_server_log_dir: "{{ mount_path }}/log/drone-server"
drone_server_data_dir: "{{ mount_path }}/var/lib/drone-server"


drone_server_version: "5.0.7"
## Networking/connection options
drone_server_bind: 0.0.0.0
drone_server_port: 6379
drone_server_password: "drone_password"
# Slave replication options
drone_server_min_slaves_to_write: 0
drone_server_min_slaves_max_lag: 10
drone_server_tcp_backlog: 10000
drone_server_tcp_keepalive: 20
# Max connected clients at a time
drone_server_maxclients: 30000
drone_server_timeout: 0

## Replication options
# Set slaveof just as you would in drone.conf. (e.g. "drone01 6379")
drone_server_slaveof: false
# Make slaves read-only. "yes" or "no"
drone_server_slave_read_only: "yes"
drone_server_slave_priority: 100
drone_server_repl_backlog_size: false

## Logging
drone_server_dir: /var/lib/drone
drone_server_logfile: '"/var/log/drone/drone-server.log"'

# Number of databases to allow
drone_server_databases: 16
drone_server_loglevel: notice
# Log queries slower than this many milliseconds. -1 to disable
drone_server_slowlog_log_slower_than: 10000
# Maximum number of slow queries to save
drone_server_slowlog_max_len: 128
# drone memory limit (e.g. 4294967296, 4096mb, 4gb)
drone_server_maxmemory: false
drone_server_maxmemory_policy: noeviction
drone_server_rename_commands: []
# How frequently to snapshot the database to disk
# e.g. "900 1" => 900 seconds if at least 1 key changed
drone_server_save:
  - 900 1
  - 300 10
  - 60 10000
drone_server_stop_writes_on_bgsave_error: "yes"
drone_server_rdbcompression: "yes"
drone_server_rdbchecksum: "yes"
drone_server_appendonly: "no"
drone_server_appendfilename: "appendonly.aof"
drone_server_appendfsync: "everysec"
drone_server_no_appendfsync_on_rewrite: "no"
drone_server_auto_aof_rewrite_percentage: "100"
drone_server_auto_aof_rewrite_min_size: "64mb"
drone_server_notify_keyspace_events: '""'
