---
- name: start docker-compose-drone-server
  become: true
  docker_compose:
    project_src: "{{ drone_server_opt_dir }}"
    state: present

- name: restart docker-compose-drone-server
  become: true
  docker_compose:
    project_src: "{{ drone_server_opt_dir }}"
    state: present
    restarted: yes


- name: stop docker-compose-drone-server
  become: true
  docker_compose:
    project_src: "{{ drone_server_opt_dir }}"
    state: absent




- name: start monit
  service: name=monit state=started enabled=yes

- name: reload monit
  service: name=monit state=reloaded enabled=yes

- name: restart monit
  service: name=monit state=restarted enabled=yes

- name: stop monit
  service: name=monit state=stopped enabled=yes
